analyzers:
  ros__parameters:
    path: Qbo
    battery:
      type: diagnostic_aggregator/GenericAnalyzer
      path: Battery Status
      startswith: ['battery_ctrl']
      remove_prefix: ['battery_ctrl']

    base_controller:
      type: diagnostic_aggregator/GenericAnalyzer
      path: Motors Status
      startswith: ['base_ctrl']
      remove_prefix: ['base_ctrl']

    imu_controller:
      type: diagnostic_aggregator/GenericAnalyzer
      path: IMU Status
      startswith: ['imu_ctrl']
      remove_prefix: ['imu_ctrl']

    LCD:
      type: diagnostic_aggregator/GenericAnalyzer
      path: LCD Status
      startswith: ['lcd_ctrl']
      remove_prefix: ['lcd_ctrl']

    head_pan:
      type: diagnostic_aggregator/GenericAnalyzer
      path: Head
      startswith: ['qbo_dynamixel: head_pan_joint']
      remove_prefix: ['qbo_dynamixel: ']

    head_tilt:
      type: diagnostic_aggregator/GenericAnalyzer
      path: Head
      startswith: ['qbo_dynamixel: head_tilt_joint']
      remove_prefix: ['qbo_dynamixel: ']

    orin-nx-16g:
        type: diagnostic_aggregator/GenericAnalyzer
        path: orin-nx-16g
        startswith: ['OrinA608Diag_node']
        remove_prefix: ['OrinA608Diag_node']

