qbo_arduqbo:
  ros__parameters:
      # i2c_device: "/dev/i2c-7"
      # i2c_address: 20

      port1: "/dev/ttyQboard1"
      baud1: 115200
      port2: "/dev/ttyQboard2"
      baud2: 115200
      timeout1: 3.0
      timeout2: 3.0
      enable_qboard1: true
      enable_qboard2: true

      enable_base: true
      enable_battery: true
      enable_imu_base: true
      enable_imu_head: false
      enable_lcd: true
      enable_nose: true
      enable_mouth: true
      enable_audio: true

/qbo_arduqbo/battery_ctrl:
  ros__parameters:
    topic: "battery_ctrl/battery_state"
    rate: 1.0
    error_battery_level: 11.5
    warn_battery_level: 12.2
    capacity_ah: 10.0
    battery_type: LiFePo4
    nominal_voltage: 13.2

/qbo_arduqbo/base_ctrl:
  ros__parameters:
    rate: 15.0
    topic: "base_ctrl/cmd_vel"
    odom_topic: "base_ctrl/odom"
    tf_odom_broadcast: true

/qbo_arduqbo/imu_ctrl:
  ros__parameters:
    rate: 15.0
    topic: "imu_ctrl/imu_state"

/qbo_arduqbo/lcd_ctrl:
  ros__parameters:
    rate: 1.0
    topic: "lcd_ctrl/cmd_lcd"

/qbo_arduqbo/nose_ctrl:
  ros__parameters:
    rate: 10.0
    topic: "nose_ctrl/cmd_nose"

/qbo_arduqbo/mouth_ctrl:
  ros__parameters:
    rate: 10.0
    topic: "mouth_ctrl/cmd_mouth"

/qbo_arduqbo/audio_ctrl:
  ros__parameters:
    rate: 15.0
    topic: "audio_ctrl/mic_report"

