qbo_arduqbo:
  ros__parameters:
      i2c_device: "/dev/i2c-7"
      i2c_address: 20

      port1: "/dev/ttyQboard1"
      baud1: 115200
      port2: "/dev/ttyQboard2"
      baud2: 115200
      timeout1: 3.0
      timeout2: 3.0
      enable_qboard1: true
      enable_qboard2: true

      enable_base: true
      enable_battery: true
      enable_imu_base: true
      enable_imu_head: false
      enable_lcd: true
      enable_nose: true
      enable_mouth: true

battery_ctrl:
  ros__parameters:
    topic: battery_state
    rate: 1.0
    error_battery_level: 11.5
    warn_battery_level: 12.2
    capacity_ah: 10.0
    battery_type: LiFePo4
    nominal_voltage: 13.2

base_ctrl:
  ros__parameters:
    rate: 15.0
    topic: "/cmd_vel"
    odom_topic: "/odom"
    tf_odom_broadcast: true

imu_ctrl:
  ros__parameters:
    rate: 15.0
    topic: "/imu_state"

lcd_ctrl:
  ros__parameters:
    rate: 1.0
    topic: "/cmd_lcd"

nose_ctrl:
  ros__parameters:
    rate: 10.0
    topic: "/cmd_nose"

mouth_ctrl:
  ros__parameters:
    rate: 10.0
    topic: "/cmd_mouth"

