qbo_arduqbo:
  ros__parameters:
      enable_qboard1: true
      port1: "/dev/ttyQboard1"
      baud1: 115200
      timeout1: 3.0
      enable_qboard2: true
      port2: "/dev/ttyQboard2"
      baud2: 115200
      timeout2: 3.0

      enable_base: true
      enable_battery: true
      enable_imu_base: true
      enable_lcd: true
      enable_nose: true
      enable_mouth: true
      enable_audio: false
      enable_sensors: true

/qbo_arduqbo/battery_ctrl:
  ros__parameters:
    rate: .0
    error_battery_level: 11.5
    warn_battery_level: 12.2
    capacity_ah: 10.0
    battery_type: LiFePo4
    nominal_voltage: 13.2

/qbo_arduqbo/base_ctrl:
  ros__parameters:
    rate: 15.0
    topic: "base_ctrl/cmd_vel"
    odom_topic: "base_ctrl/odom"
    tf_odom_broadcast: true

/qbo_arduqbo/imu_ctrl:
  ros__parameters:
    rate: 15.0
    topic: "imu_ctrl/imu_state"

/qbo_arduqbo/lcd_ctrl:
  ros__parameters:
    rate: 1.0
    topic: "lcd_ctrl/cmd_lcd"

/qbo_arduqbo/nose_ctrl:
  ros__parameters:
    rate: 10.0
    topic: "nose_ctrl/cmd_nose"

/qbo_arduqbo/mouth_ctrl:
  ros__parameters:
    rate: 10.0
    topic: "mouth_ctrl/cmd_mouth"

/qbo_arduqbo/audio_ctrl:
  ros__parameters:
    rate: 15.0
    topic: "audio_ctrl/mic_report"

/qbo_arduqbo/sens_ctrl:
  ros__parameters:
    rate: 15.0
    topic: "sens_ctrl/distance_sensors_state"

    sensors.front.front_left_srf10.type: "srf10"
    sensors.front.front_left_srf10.address: 112
    sensors.front.front_left_srf10.frame_id: "front_left_addon"
    sensors.front.front_left_srf10.publish_if_obstacle: true

    sensors.front.front_right_srf10.type: "srf10"
    sensors.front.front_right_srf10.address: 113
    sensors.front.front_right_srf10.frame_id: "front_right_addon"
    sensors.front.front_right_srf10.publish_if_obstacle: true

    sensors.back.back_left_srf10.type: "srf10"
    sensors.back.back_left_srf10.address: 114
    sensors.back.back_left_srf10.frame_id: "back_left_addon"
    sensors.back.back_left_srf10.publish_if_obstacle: true

    sensors.back.back_right_srf10.type: "srf10"
    sensors.back.back_right_srf10.address: 115
    sensors.back.back_right_srf10.frame_id: "back_right_addon"
    sensors.back.back_right_srf10.publish_if_obstacle: true

    sensors.front.floor_sensor.type: "GP2Y0A21YK"
    sensors.front.floor_sensor.address: 8
    sensors.front.floor_sensor.frame_id: "front_addon"
    sensors.front.floor_sensor.publish_if_obstacle: false

