# aggregator_node:
#   ros__parameters:
#     analyzers:
#       qbo_diag:
#         type: "diagnostic_aggregator/GenericAnalyzer"
#         path: "QBO"
#         startswith: "QBO/"
#         remove_prefix: "QBO/"
#         expected:
#           - "RAM Usage (G)"
#           - "CPU Temperature (Â°C)"
#           - "GPU Load (%)"
#           - "Fan PWM (%)"
#           - "Power Total (W)"
#           - "Disk Usage (%)"
# analyzers:
#   path: Qbo
#   orin-nx-16g:
#     type: diagnostic_aggregator/GenericAnalyzer
#     path: orin-nx-16g
#     startswith: ['QBO Diagnostics [orin-nx-16g]']
#     remove_prefix: ['QBO Diagnostics [orin-nx-16g]']

diagnostic_aggregator:
  ros__parameters:
    analyzers:
      orin-nx-16g:
        type: diagnostic_aggregator/GenericAnalyzer
        path: orin-nx-16g
        startswith: ['QBO Diagnostics [orin-nx-16g]']
        remove_prefix: ['QBO Diagnostics [orin-nx-16g]']
