/qbo_talk_coqui:
  ros__parameters:
    sample_rate: 16000
    output_channels: 2
    audio_playback_volume: 100

    # TTS
    default_lang: "fr"
    tts_model_name: "tts_models/multilingual/multi-dataset/your_tts"
    tts_speaker: "male-en-2"
    tts_language_fr: "fr-fr"
    tts_language_en: "en"
    use_gpu: true
    warmup_text: "Bonjour."
    queue_maxsize: 10
    tts_speaker_wav: "/home/qbo-v2/venvs/tts/qbo_fr_ref_22050.wav"
    speech_rate: 0.8

    # Carte son
    speaker_device: "ReSpeaker XVF3800"  # ALSA device name (ex: "hw:0,0" ou "default")
    speaker_volume: 100

    # RMS cible - anti-pop
    target_rms: 0.22
    max_peak: 0.98
    soft_limit: 1.5
