diagnostic:

  orin-nx-16g:

    RAM:
      name: "RAM Usage"
      unit: "G"
      threshold: 15
      enabled: true

    TEMPERATURE CPU:
      name: "CPU Temperature"
      unit: "Â°C"
      threshold: 75
      enabled: true

    GPU USAGE:
      name: "GPU Load"
      unit: "%"
      threshold: 90
      enabled: true

    FAN SPEED:
      name: "Fan PWM"
      unit: "%"
      threshold: 90
      enabled: true

    POWER TOTAL:
      name: "Power Total"
      unit: "W"
      threshold: 50
      enabled: true

    DISK USAGE:
      name: "Disk Usage"
      unit: "%"
      threshold: 80
      enabled: true
