qbo_face_following:
  ros__parameters:
    move_base: false
    move_head: true
    search_min_pan: -0.3
    search_max_pan: 0.3
    search_pan_vel: 0.3
    search_min_tilt: 0.7
    search_max_tilt: 0.7
    search_tilt_vel: 0.3
    desired_distance: 1.0
    send_stop: true
