qbo_face_recognizer:
  ros__parameters:
    path_faces_learn: "/home/qbo-v2/qbo_ws/src/qbo_vision/faces/learn"         # Dossier où sont enregistrés les visages inconnus (à renommer manuellement)
    path_model_file: "/home/qbo-v2/qbo_ws/src/qbo_vision/faces/model"          # Dossier où sera enregistré le fichier du modèle LBPH entraîné
    model_file: "face_model.xml"            # Nom du fichier de modèle LBPH
    confidence_threshold: 65.0              # Seuil maximum de confiance pour reconnaître un visage (plus petit = plus strict)
