image_width: 800
image_height: 600
camera_name: left_camera
camera_matrix:
  rows: 3
  cols: 3
  data: [563.84755,   0.     , 408.61475,
           0.     , 564.28267, 277.86022,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.059954, -0.076382, -0.005926, -0.003378, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [570.41779,   0.     , 405.34025,   0.     ,
           0.     , 570.86505, 273.90589,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
