image_width: 640
image_height: 480
camera_name: left_camera
camera_matrix:
  rows: 3
  cols: 3
  data: [462.30622,   0.     , 327.19288,
           0.     , 462.88321, 233.05944,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.059160, -0.069859, 0.001681, -0.002006, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [467.51282,   0.     , 325.41508,   0.     ,
           0.     , 468.39291, 233.30164,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
